# Generated by Django 3.0.5 on 2020-05-27 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('CT', 'Completed')], max_length=2)),
                ('doc', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='doctor.DoctorProfile')),
                ('pat', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='patient.PatientProfile')),
            ],
            options={
                'unique_together': {('time', 'date', 'pat', 'doc')},
            },
        ),
    ]
