# Generated by Django 3.0.5 on 2020-05-27 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('reception', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='patient.PatientProfile'),
        ),
    ]
