# Generated by Django 3.0.5 on 2020-05-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='Blood Group',
            new_name='Blood_Group',
        ),
        migrations.RenameField(
            model_name='patientprofile',
            old_name='Case Paper no.',
            new_name='Case_Paper_no',
        ),
        migrations.RenameField(
            model_name='patientprofile',
            old_name='Profile Picture',
            new_name='Profile_Picture',
        ),
    ]
